# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='知名高校', max_length=10, verbose_name='机构标签'),
        ),
    ]
